### ISSUE TITLE
Compose a well-thought out general .gitignore file

### ISSUE THREAD

**Issue by ZenaMel** [Zenahr/lazystarter#30]

**Comment by ZenaMel** [comment]
Any thoughts on the content of the .gitignore file yet?

**Comment by JacobRockhold** [comment]
I didn't understand it as well as I thought I did. I would like to continue working on it since I am learning. The idea I had was to just combine gitignore files from the gitignore repo, but so far the tests I have done aren't turning out the way I want. Files are still included and I can't figure out why.
